"""empty message

Revision ID: 55477c6896f2
Revises: c927dba625ed
Create Date: 2022-08-20 20:16:34.944299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55477c6896f2'
down_revision = 'c927dba625ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.drop_column('Venue', 'looking_for_talent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('looking_for_talent', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('Venue', 'seeking_talent')
    # ### end Alembic commands ###
